name: apple-aarch64-test

on:
  push:
    branches: [dev, mc]
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    - name: make test
      run: |
         uname -a
         make test
