name: make-bench

on: [workflow_dispatch]
#  schedule:
#    # Run at 18:00 UTC on Wednesday
#    - cron:  '00 18 * * 3'

jobs:
  bench:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.arch }} ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: bench
      run: make -C src bench
