name: zig-bench

on: [workflow_dispatch]
#  schedule:
#    # Run at 18:00 UTC on Wednesday
#    - cron:  '00 18 * * 3'

jobs:
  bench:

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.arch }} ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
      with:
        version: "0.16.0"
    - name: bench
      run: zig build bench
